const API_BASE_URL_DEVELOPEMENT = 'https://localhost:7101';
const API_BASE_URL_PRODUCTION = 'https://appname.azurewebsites.net';


const ENDPOINTS = {
    GET_ALL_BOOKS: 'api/books/',
    GET_BOOK_BY_ID: 'api/books/{id:guid}',
    CREATE_BOOK: 'api/createbook/',
    UPDATE_BOOK: 'api/updateBook/',
    DELETE_BOOK_BY_ID: 'api/deleteBook'
};

const development = {
    API_URL_GET_ALL_BOOKS: `${API_BASE_URL_DEVELOPEMENT}/${ENDPOINTS.GET_ALL_BOOKS}`,
    API_URL_GET_BOOK_BY_ID: `${API_BASE_URL_DEVELOPEMENT}/${ENDPOINTS.GET_BOOK_BY_ID}`,
    API_URL_CREATE_BOOK: `${API_BASE_URL_DEVELOPEMENT}/${ENDPOINTS.CREATE_BOOK}`,
    API_URL_UPDATE_BOOK: `${API_BASE_URL_DEVELOPEMENT}/${ENDPOINTS.UPDATE_BOOK}`,
    API_URL_DELETE_BOOK_BY_ID: `${API_BASE_URL_DEVELOPEMENT}/${ENDPOINTS.DELETE_BOOK_BY_ID}`,
};

const production = {
    API_URL_GET_ALL_BOOKS: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_ALL_BOOKS}`,
    API_URL_GET_BOOK_BY_ID: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_BOOK_BY_ID}`,
    API_URL_CREATE_BOOK: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.CREATE_BOOK}`,
    API_URL_UPDATE_BOOK: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.UPDATE_BOOK}`,
    API_URL_DELETE_BOOK_BY_ID: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.DELETE_BOOK_BY_ID}`,
};

const Constants = process.env.NODE_ENV === 'development' ? development : production;

export default Constants;